### ISSUE TITLE
MM2? Is it even possible?

### ISSUE THREAD

**Issue by k9lego** [Tarnadas/smmdb#19]
I'm quite curious, are you aware of any potential ways that a similar API like this could be made for Super Mario Maker 2? What I'm looking for (might not be possible lol) is a way to send a level ID for MM2, and get some statistics and an image of the level.

**Comment by Tarnadas** [comment]
MM2 levels will be supported as well, but they need to be reverse engineered first. They already got decrypted by someone I'm in touch with.

What you are looking for doesn't work, because you are referring to the level ID given by Nintendo servers

**Comment by k9lego** [comment]
Gotcha, that's cool.
But the whole idea being you input the level Id and it returns info about the level, will that be possible through this third-party unsupported API in the future? :P

**Comment by Tarnadas** [comment]
Unlikely. Someone RE the first part of MM1 level ID, but we don't know how Nintendo generates the level IDs

**Comment by neurodiverseEsoteric** [comment]
So uploading bcd files still isn't possible?

**Comment by Tarnadas** [comment]
oh lol sorry :D
It has been possible for a long time now. You will however need to package your course into an e.g. zip container and upload it with the thumbnail.

The thing with the original level ID is not possible as seen above and is very unlikely to ever work.

**Comment by neurodiverseEsoteric** [comment]
Ah okay...I tried uploading a zip file but every time I refresh it dissappears...

**Comment by Tarnadas** [comment]
Someone on our Discord server reported this as well. Can you send me this zip file please so that I can test it locally?

**Comment by Tarnadas** [comment]
You can also try inserting it here:
https://tarnadas.github.io/smmdb-lib/

It will display smm2 courses that it finds and it all runs locally in your browser

**Comment by neurodiverseEsoteric** [comment]
[01009B90006DC000_1.zip](https://github.com/Tarnadas/smmdb/files/5970053/01009B90006DC000_1.zip)
[01009B90006DC000.zip](https://github.com/Tarnadas/smmdb/files/5970054/01009B90006DC000.zip)

Here you go, the _1 version has the desired level title since I wasn't sure how to rename slots, but the original one should have the clear playthrough, I hope?
