### ISSUE TITLE
Navigation doesnt work

### ISSUE THREAD

**Issue by EzioisAwesome56** [Tarnadas/smmdb#2]
okay, so if I click the navigation button, nothing opens. I am using firefox 47 on windows 10. could you please look into this

**Comment by Tarnadas** [comment]
It's because of a bug prior to Firefox < 51.
See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Gecko_note_2)

Could you consider updating Firefox?

**Comment by EzioisAwesome56** [comment]
no, I probably dont have enough disk space to do so, however I have firefox 57 on my mac, I can go test it there for you

**Comment by EzioisAwesome56** [comment]
Okay, tested on the lasted version of firefox on mac (like 57 or something) and it works fine

I do recommend that you add some kind of fallback though,
