### ISSUE TITLE
smmdb.net down?

### ISSUE THREAD

**Issue by Sp4wnf3rk3l** [Tarnadas/smmdb#36]
Hey Mate,

first of all: Thx! I'm using your software since Cemu-times :D

Recently i tried the yuzu emulator with smm2 and tested your
program. Unfortunately it shows an error:

"FetchError: expected value at line 1 column 1"

is this because smmdb.net is down? will you come back?^^

Regards

Sp4wnf3rk3l

**Comment by Tarnadas** [comment]
Hey, yeah sorry there was a misconfiguration in the server Startup script. It is now fixed and back online.

also thanks for notifying me!

**Comment by Sp4wnf3rk3l** [comment]
im the one who has to be thankful :)

so thx! :D
